# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57393df9957179b93c1fdb5afcd6b1070a6f03336a591b1882739eb890fb6299092468f51b9000a0da322504b86f8fc23ffcf4abda97ec7f285e829a44100fdb

test:
  secret_key_base: babe1a2dd0d8521934176334d564c97c0e7521ff893e14540bb4f18a215a395079fb93d21f8c8edb52910659517f0504081d097afa9f16bd53878626fa82a436

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
